"""
fda_importer.py — Convert real FDA enforcement documents into calibration items.

Sources supported
-----------------
- FDA Warning Letters  (HTML, publicly available)
- FDA 483 observations (plain text pasted or loaded from file)
- Any raw regulatory enforcement text

Workflow
--------
1. Fetch document text from a URL or file path
2. LLM reads the document and extracts distinct compliance observations
3. Each observation becomes a task dict with source_type="real"
4. Tasks enter the normal calibration pipeline (Calibrator + Database)

Why this matters
----------------
Synthetic items are generated by the same LLM that solves them, creating a
closed loop. Real FDA enforcement documents represent actual compliance failures
that real companies made and FDA officially cited. Items derived from them have
ground-truth difficulty grounded in regulatory practice, not model priors.

Usage
-----
    python fda_importer.py --url <fda_warning_letter_url>
    python fda_importer.py --file <path_to_text_file>
    python fda_importer.py --url <url> --dry-run   # extract only, no calibration
"""

import argparse
import html
import json
import os
import re
import sys
import textwrap
import urllib.request
import uuid
from pathlib import Path

import openai

from calibrator import Calibrator
from database import Database


# ---------------------------------------------------------------------------
# Document fetching
# ---------------------------------------------------------------------------

_USER_AGENT = (
    "Mozilla/5.0 (compatible; research-bot/1.0; +compliance-irt-research)"
)

def fetch_url(url: str) -> str:
    """
    Fetch a URL and return its content as plain text.
    Strips HTML tags if the response looks like HTML.
    """
    req = urllib.request.Request(url, headers={"User-Agent": _USER_AGENT})
    with urllib.request.urlopen(req, timeout=30) as resp:
        raw = resp.read().decode("utf-8", errors="replace")
    return _strip_html(raw) if "<html" in raw.lower() else raw


def _strip_html(html_text: str) -> str:
    """
    Minimal HTML → plain text conversion without external deps.
    Preserves paragraph structure; removes tags, scripts, styles.
    """
    # Remove script and style blocks
    text = re.sub(r"<(script|style)[^>]*>.*?</\1>", "", html_text,
                  flags=re.DOTALL | re.IGNORECASE)
    # Replace block-level tags with newlines
    text = re.sub(r"<(br|p|li|tr|h[1-6]|div)[^>]*/?>", "\n", text,
                  flags=re.IGNORECASE)
    # Strip remaining tags
    text = re.sub(r"<[^>]+>", "", text)
    # Decode HTML entities
    text = html.unescape(text)
    # Collapse whitespace
    text = re.sub(r"\n{3,}", "\n\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    return text.strip()


def load_file(path: str) -> str:
    return Path(path).read_text(encoding="utf-8", errors="replace").strip()


# ---------------------------------------------------------------------------
# Conversion prompts
# ---------------------------------------------------------------------------

_CONVERTER_SYSTEM = (
    "You are a biopharma regulatory affairs specialist and instructional designer. "
    "Your task is to read real FDA enforcement documents (warning letters, 483 observations) "
    "and convert each distinct compliance finding into a structured exam-quality scenario. "
    "You extract the facts faithfully — you do not invent or embellish. "
    "You anonymize company names by replacing them with fictional names (e.g., 'NovaBio Inc.'). "
    "Every item you produce must be grounded in the actual regulatory citation from the document."
)

_CONVERTER_USER = """
Below is the text of an FDA enforcement document (warning letter or 483 observation).

Read it carefully and extract up to {max_items} distinct compliance findings.
For each finding, produce one JSON object in this exact structure:

{{
  "domain": "<one of: 21cfr11 | gcp_deviation | promo_review | gmp_deviation | informed_consent | gmp_general | other>",
  "context": "<3-5 sentences describing the situation faithfully but with the real company name replaced by a fictional one. Include concrete details: roles, systems, dates if available, quantities. Do not state the compliance conclusion.>",
  "question": "<One precise question asking whether the described practice is compliant, or what the correct regulatory action is. Must have a single defensible answer.>",
  "gold_standard": "<The correct answer. Must cite the EXACT regulation section(s) that FDA cited in the document (e.g., '21 CFR 211.192', 'ICH E6(R2) §5.18.2'). State the specific obligation or violation precisely.>",
  "source_observation": "<Direct quote or close paraphrase of the key sentence(s) from the original document that this item is based on. Keep under 200 characters.>"
}}

Rules:
- Output a JSON array containing between 1 and {max_items} objects. Nothing else — no markdown, no commentary.
- Each item must correspond to a distinct observation in the document.
- Do not invent findings not present in the document.
- If the document does not contain clear regulatory citations, still extract the finding and note the likely applicable regulation based on the subject matter.
- Anonymize all real company names, product names, and individual names.
- Do not include the compliance conclusion in context or question fields.

--- FDA DOCUMENT ---
{document_text}
"""


# ---------------------------------------------------------------------------
# Converter class
# ---------------------------------------------------------------------------

class FDAConverter:
    """
    Extracts compliance scenarios from real FDA enforcement documents.

    Parameters
    ----------
    client      : openai.OpenAI  (pointed at Groq or any OpenAI-compatible endpoint)
    model       : LLM to use for extraction
    max_items   : Maximum number of items to extract per document
    """

    def __init__(
        self,
        client: openai.OpenAI,
        model: str = "llama-3.3-70b-versatile",
        max_items: int = 5,
    ) -> None:
        self.client    = client
        self.model     = model
        self.max_items = max_items

    def convert(self, document_text: str, source_ref: str = "") -> list[dict]:
        """
        Extract compliance items from document text.

        Returns a list of task dicts ready for calibration, tagged with
        source_type="real" and source_ref=<url or filename>.
        """
        # Truncate very long documents to avoid context limits
        text = document_text[:12_000] if len(document_text) > 12_000 else document_text

        prompt = _CONVERTER_USER.format(
            max_items=self.max_items,
            document_text=text,
        )

        try:
            resp = self.client.chat.completions.create(
                model=self.model,
                max_tokens=4096,
                messages=[
                    {"role": "system", "content": _CONVERTER_SYSTEM},
                    {"role": "user",   "content": prompt},
                ],
            )
            raw = resp.choices[0].message.content.strip()
        except Exception as exc:
            print(f"  [FDAConverter] API error: {exc}")
            return []

        items = self._parse(raw)
        tasks = []
        for item in items:
            domain  = item.get("domain", "other")
            task_id = f"TASK-REAL-{domain.upper()[:8]}-{uuid.uuid4().hex[:8].upper()}"
            tasks.append({
                "task_id":          task_id,
                "domain":           domain,
                "context":          item.get("context", ""),
                "question":         item.get("question", ""),
                "gold_standard":    item.get("gold_standard", ""),
                "source_type":      "real",
                "source_ref":       source_ref,
                "source_observation": item.get("source_observation", ""),
            })
        return tasks

    # ------------------------------------------------------------------
    # Internal
    # ------------------------------------------------------------------

    @staticmethod
    def _parse(raw: str) -> list[dict]:
        """Parse JSON array from LLM response, tolerating markdown fences."""
        cleaned = re.sub(r"^```(?:json)?\s*", "", raw, flags=re.MULTILINE)
        cleaned = re.sub(r"\s*```$",          "", cleaned, flags=re.MULTILINE)
        cleaned = cleaned.strip()

        # Model sometimes returns a single object instead of an array
        if cleaned.startswith("{"):
            cleaned = f"[{cleaned}]"

        try:
            return json.loads(cleaned)
        except json.JSONDecodeError as exc:
            print(f"  [FDAConverter] JSON parse error: {exc}")
            print(f"  Raw response (first 500 chars): {raw[:500]}")
            return []


# ---------------------------------------------------------------------------
# Analysis helpers
# ---------------------------------------------------------------------------

def _mean(values: list[float]) -> float:
    return sum(values) / len(values) if values else float("nan")

def _stdev(values: list[float]) -> float:
    if len(values) < 2:
        return float("nan")
    m = _mean(values)
    return (sum((x - m) ** 2 for x in values) / (len(values) - 1)) ** 0.5

def print_comparison(db: Database) -> None:
    """
    Print a side-by-side difficulty distribution comparison:
    real-world items vs. synthetic items.
    """
    groups = db.fetch_b_by_source()
    synth  = sorted(groups.get("synthetic", []))
    real   = sorted(groups.get("real", []))

    bar_width = 40

    def histogram(values: list[float], lo: float = -3.0, hi: float = 3.0,
                  bins: int = 12) -> str:
        if not values:
            return "  (no data)"
        bin_size  = (hi - lo) / bins
        counts    = [0] * bins
        for v in values:
            idx = min(int((v - lo) / bin_size), bins - 1)
            idx = max(0, idx)
            counts[idx] += 1
        max_count = max(counts) or 1
        lines = []
        for i, c in enumerate(counts):
            label = f"{lo + i * bin_size:+.1f}"
            bar   = "█" * int(bar_width * c / max_count)
            lines.append(f"  {label:>6}  {bar:<{bar_width}}  {c}")
        return "\n".join(lines)

    width = 64
    bar   = "─" * width

    print(f"\n{bar}")
    print(f"  Difficulty (b) Distribution: Real vs. Synthetic")
    print(bar)

    print(f"\n  SYNTHETIC  (N={len(synth)} retained items)")
    if synth:
        print(f"  mean={_mean(synth):.3f}  sd={_stdev(synth):.3f}"
              f"  min={min(synth):.3f}  max={max(synth):.3f}")
    print(histogram(synth))

    print(f"\n  REAL-WORLD (N={len(real)} retained items)")
    if real:
        print(f"  mean={_mean(real):.3f}  sd={_stdev(real):.3f}"
              f"  min={min(real):.3f}  max={max(real):.3f}")
    print(histogram(real))

    if synth and real:
        delta = _mean(real) - _mean(synth)
        print(f"\n  Mean b gap (real − synthetic): {delta:+.3f}")
        if delta > 0.3:
            print("  Real items appear harder on average than synthetic items.")
        elif delta < -0.3:
            print("  Real items appear easier on average than synthetic items.")
        else:
            print("  Real and synthetic item difficulty are broadly similar.")
    print(bar)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def _parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description=(
            "Import real FDA enforcement documents into the compliance item bank. "
            "Fetches or reads a document, extracts compliance scenarios, calibrates "
            "them with the Vanilla/Augmented solvers, and stores them tagged as "
            "source_type='real'."
        )
    )
    src = p.add_mutually_exclusive_group(required=True)
    src.add_argument("--url",  help="URL of an FDA warning letter or enforcement document")
    src.add_argument("--file", help="Path to a local text file containing the document")

    p.add_argument("--db",        default="compliance_bank.db",
                   help="SQLite database path (default: compliance_bank.db)")
    p.add_argument("--max-items", type=int, default=5,
                   help="Max compliance items to extract per document (default: 5)")
    p.add_argument("--dry-run",   action="store_true",
                   help="Extract and display items but do not calibrate or save")
    p.add_argument("--quiet",     action="store_true",
                   help="Suppress per-step solver logs")
    p.add_argument("--compare",   action="store_true",
                   help="After import, print real vs. synthetic difficulty comparison")
    return p.parse_args()


def _print_task_card(task: dict) -> None:
    print(f"\n  Task ID  : {task['task_id']}")
    print(f"  Domain   : {task['domain']}")
    print(f"  Source   : {task.get('source_ref', 'unknown')}")
    if task.get("source_observation"):
        print(f"  FDA obs  : {task['source_observation'][:120]}")
    print(f"  Context  :\n{textwrap.fill(task['context'], width=78, initial_indent='    ', subsequent_indent='    ')}")
    print(f"  Question :\n{textwrap.fill(task['question'], width=78, initial_indent='    ', subsequent_indent='    ')}")
    print(f"  Gold Std :\n{textwrap.fill(task['gold_standard'], width=78, initial_indent='    ', subsequent_indent='    ')}")


def main() -> None:
    args = _parse_args()

    api_key = os.environ.get("GROQ_API_KEY")
    if not api_key:
        print("ERROR: GROQ_API_KEY environment variable is not set.")
        sys.exit(1)

    client = openai.OpenAI(
        base_url="https://api.groq.com/openai/v1",
        api_key=api_key,
    )

    # -- Fetch document ---------------------------------------------------
    if args.url:
        print(f"\n  Fetching: {args.url}")
        try:
            text = fetch_url(args.url)
        except Exception as exc:
            print(f"  ERROR fetching URL: {exc}")
            sys.exit(1)
        source_ref = args.url
    else:
        print(f"\n  Reading: {args.file}")
        text = load_file(args.file)
        source_ref = args.file

    print(f"  Document length: {len(text):,} characters")

    # -- Extract items ----------------------------------------------------
    print(f"\n  Extracting up to {args.max_items} compliance items…")
    converter = FDAConverter(client, max_items=args.max_items)
    tasks     = converter.convert(text, source_ref=source_ref)

    if not tasks:
        print("  No items extracted. Check the document format and try again.")
        sys.exit(1)

    print(f"\n  Extracted {len(tasks)} item(s):\n")
    for task in tasks:
        _print_task_card(task)

    if args.dry_run:
        print("\n  [dry-run] Skipping calibration and database write.")
        return

    # -- Calibrate --------------------------------------------------------
    db         = Database(args.db)
    calibrator = Calibrator(client, verbose=not args.quiet)

    print(f"\n{'─' * 64}")
    print(f"  Calibrating {len(tasks)} real-world item(s)…")
    print(f"{'─' * 64}")

    for task in tasks:
        db.insert_task(task)
        result = calibrator.calibrate(task)
        db.insert_calibration_result(result)

        status = result["retention_reason"]
        b_str  = f"b={result['irt_b']:.4f}" if result["irt_b"] is not None else "b=n/a"
        print(
            f"  {task['task_id']}  →  {status}  {b_str}"
            f"  [V:{'P' if result['vanilla_pass'] else 'F'}"
            f"  A:{'P' if result['augmented_pass'] else 'F'}]"
        )

    # -- Comparison -------------------------------------------------------
    if args.compare:
        print_comparison(db)

    print(f"\n  Done. {len(tasks)} real-world item(s) added to {args.db}.")


if __name__ == "__main__":
    main()
